"""A browsable overview of the site's existing free activities."""
def render(page):
    items=[
      ('Play online','🦄','Unicorn memory','Choose an easy three-pair game or the classic six-pair challenge. No timer, with a fresh shuffle each game.','Phone or computer · 1 player or take turns','/tools/unicorn-memory-game.html','Play memory'),
      ('Print and play','✨','Unicorn treasure hunt','Hide six picture cards, then tick off matching symbols. Includes cards, a player sheet and setup instructions.','Printer and pencils · solo or group','/tools/unicorn-treasure-hunt.html','Get the treasure hunt'),
      ('Party game','🌈','Unicorn bingo','Generate different word cards for up to 12 players and use the on-screen caller to host your game.','Printer · readers or adult helpers','/tools/unicorn-party-games.html#bingo','Make bingo cards'),
    ]
    cards=''.join(f'<article class="activity-card"><div class="activity-preview" aria-hidden="true">{icon}</div><span class="eyebrow">{kind}</span><h2>{title}</h2><p>{description}</p><p class="field-help">{requirements}</p><a class="button" href="{url}">{cta}</a></article>' for kind,icon,title,description,requirements,url,cta in items)
    body='''<main id="main"><div class="page-intro"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / Free activities</div><span class="eyebrow">Play · Print · Plan</span><h1>Free unicorn games &amp; printables</h1><p>Pick a quick browser game, a picture treasure hunt or bingo for your next party. All three are free to use and need no account.</p></div></div><div class="wrap activities-page"><div class="activity-grid">'''+cards+'''</div><aside class="callout"><h2>Ready to print?</h2><p>Get six hiding cards and a matching player sheet in one free, two-page PDF. No sign-up needed.</p><a class="button" href="/assets/downloads/unicorn-treasure-hunt.pdf" download>Download the treasure hunt PDF</a></aside><section class="article"><h2>Which activity should you choose?</h2><dl class="activity-choices"><dt>No printer?</dt><dd>Play <a href="/tools/unicorn-memory-game.html">memory online</a>. You can also draw the treasure-hunt symbols on paper.</dd><dt>Children not reading yet?</dt><dd>Try the <a href="/tools/unicorn-treasure-hunt.html">picture treasure hunt</a> with an adult helper. Match shapes rather than words.</dd><dt>A seated group activity?</dt><dd>Use <a href="/tools/unicorn-party-games.html#bingo">word bingo</a> with a helper for younger players.</dd></dl><h2>Turn the games into a party plan</h2><p>Start with the treasure hunt, pause for cake, then settle down for bingo. Adjust the order to suit your group and space.</p><div class="callout"><p><a href="/tools/unicorn-party-planner.html">Estimate supplies and your budget</a> · <a href="/tools/birthday-cake-servings-calculator.html">Plan the unicorn cake</a> · <a href="/tools/unicorn-party-games.html#choose-game">Compare party activities and supplies</a></p></div><h2>Questions before you start</h2><details><summary>Do I need to register or pay?</summary><p>No. These activities do not require an account or payment. Printing uses your own paper and ink; supplies and optional items from shops are separate.</p></details><details><summary>Can I save the printables as a PDF?</summary><p>The treasure hunt has a ready-made <a href="/assets/downloads/unicorn-treasure-hunt.pdf">two-page PDF download</a>. For bingo, generate your cards, choose the print button, then select Save as PDF in your browser's print options where available.</p></details><details><summary>Are game scores saved?</summary><p>No. Memory starts over when you reload. Bingo cards and caller progress are also cleared when you reload; print the cards before playing.</p></details></section></div></main>'''
    return page('Free Unicorn Games & Printables | Unicorn Finds','Play unicorn memory online or print free treasure-hunt and bingo activities. Choose by group, reading level and equipment, with no account needed.','/tools/free-unicorn-games.html',body).replace('</head>','<link rel="stylesheet" href="/assets/activities.css"></head>')
