"""Free printable invitation maker and practical invitation guide."""
def render(page):
    body='''<main id="main"><div class="page-intro"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / <a href="/tools/free-unicorn-games.html">Free activities</a></div><span class="eyebrow">Make · Print · Celebrate</span><h1>Free printable unicorn birthday invitations</h1><p>Make a simple unicorn party invitation with your own details. Print one invitation per page or save it as a PDF using your browser. No account needed.</p><a class="button" href="#invitation-maker">Make your invitation</a></div></div>
<div class="wrap invitation-page"><section id="invitation-maker" class="invitation-layout"><div class="invitation-controls"><h2>Add your party details</h2><p>Use a first name or nickname. Your entries stay in this page and are not saved by the invitation tool. Reloading clears them.</p><form id="invite-form">
<label for="invite-name">Birthday name <span>(optional)</span></label><input id="invite-name" maxlength="40" placeholder="Alex">
<label for="invite-date">Date <span>(include the year)</span></label><input id="invite-date" maxlength="60" placeholder="Saturday, 12 June 2027">
<label for="invite-time">Start and finish time</label><input id="invite-time" maxlength="60" placeholder="2:00–4:00 pm">
<label for="invite-place">Place</label><input id="invite-place" maxlength="100" placeholder="Party venue and address">
<label for="invite-rsvp">RSVP contact and deadline</label><input id="invite-rsvp" maxlength="100" placeholder="Please reply to the host by 5 June">
<label for="invite-note">Extra note <span>(optional)</span></label><input id="invite-note" maxlength="100" placeholder="Please tell the host about dietary needs">
<div class="hero-actions"><button class="button" id="invite-print" type="button" hidden>Print / save PDF</button><button class="button button-light" type="reset">Clear details</button></div></form>
<p class="field-help">Check every detail in the preview before printing. In the print dialog, choose portrait, A4 or Letter, and turn off headers and footers. Select Save as PDF where available.</p><noscript><p>Enable JavaScript to personalize the invitation. You can still print this blank template from your browser and fill it in by hand.</p></noscript></div>
<article id="invite-card" aria-label="Invitation preview"><div class="invite-stars" aria-hidden="true">✦ ⋆ ✧ ⋆ ✦</div><div class="invite-unicorn" aria-hidden="true">🦄</div><p class="invite-kicker">A little magic, a lot of fun</p><h2>You're invited!</h2><p id="preview-name" class="invite-name">To a unicorn birthday party</p><dl><dt>Date</dt><dd id="preview-date">________________________________</dd><dt>Time</dt><dd id="preview-time">________________________________</dd><dt>Place</dt><dd id="preview-place">________________________________</dd><dt>RSVP</dt><dd id="preview-rsvp">________________________________</dd></dl><p id="preview-note" class="invite-note">We can't wait to celebrate with you!</p><p class="invite-credit">Made with unicornsite.online</p></article></section>
<section class="article"><h2>What to put on a unicorn party invitation</h2><p>A useful invitation makes the practical details easy to find. Include the full date, a start and finish time, the venue address, and a way to reply. If parents should stay, or if the party is a drop-off event, say so in the extra note.</p><h3>Copy this invitation wording</h3><blockquote>You're invited to a magical unicorn birthday party! Join us on [date] from [start] to [finish] at [place]. Please RSVP to [host] by [deadline], and let us know about any dietary needs.</blockquote><p>For a small gathering, you can replace the birthday line with “Join us for a unicorn afternoon.” Keep the invitation brief; send directions and any longer instructions separately.</p>
<h2>Printing and sharing your invitation</h2><ol><li>Fill in the form and check the preview. Fields left empty become writing lines.</li><li>Choose Print / save PDF. The print layout includes only the invitation.</li><li>Print one test page first. Use normal paper or cardstock that your printer supports.</li><li>For a digital invitation, choose Save as PDF and send the file privately to your guests. This tool does not send invitations for you.</li></ol><p>Only share a version containing an address or contact details with your intended guests. Free for personal party use.</p>
<h2>Plan what happens after the invitation</h2><p>Use the <a href="/tools/unicorn-party-planner.html">unicorn party planner</a> to estimate supplies, make a <a href="/tools/birthday-cake-servings-calculator.html">cake servings plan</a>, then pick <a href="/tools/free-unicorn-games.html">free games and printables</a>. Our <a href="/guides/unicorn-party-favor-ideas.html">party favor guide</a> helps compare optional extras.</p>
<h2>Invitation questions</h2><details><summary>Can I make an invitation without entering personal details?</summary><p>Yes. Leave the fields blank and print a template to fill in by hand.</p></details><details><summary>Can I print several invitations?</summary><p>Yes. Choose the number of copies in your printer's dialog. Each copy uses one page.</p></details><details><summary>Will my invitation be saved?</summary><p>No. The tool does not save your entries or put them in the page address. Save your finished invitation as a PDF before closing or reloading the page.</p></details></section></div><script src="/assets/invitations.js" defer></script></main>'''
    return page('Free Unicorn Birthday Invitation Maker | Unicorn Finds','Create a free printable unicorn birthday invitation. Add party details, preview your design, then print or save as PDF. No sign-up needed.','/tools/unicorn-birthday-invitations.html',body).replace('</head>','<link rel="stylesheet" href="/assets/invitations.css"></head>')
