"""Original printable matching game; all artwork is inline vector geometry."""
SYMBOLS = [
 ('Star', '<path d="m50 8 12 27 30 3-23 21 7 30-26-16-26 16 7-30L8 38l30-3Z"/>'),
 ('Heart', '<path d="M50 85 15 51C-8 22 27 2 50 27 73 2 108 22 85 51Z"/>'),
 ('Moon', '<path d="M65 10A40 40 0 1 0 90 70 36 36 0 0 1 65 10Z"/>'),
 ('Rainbow', '<path d="M10 80V55a40 40 0 0 1 80 0v25H75V55a25 25 0 0 0-50 0v25Z"/><path d="M34 80V55a16 16 0 0 1 32 0v25H55V55a5 5 0 0 0-10 0v25Z"/>'),
 ('Cloud', '<path d="M23 77a19 19 0 0 1-3-38 28 28 0 0 1 53-9 24 24 0 0 1 4 47Z"/>'),
 ('Crystal', '<path d="m50 7 28 23v40L50 93 22 70V30Z"/><path d="M22 30h56L50 93 22 30 50 7v86" fill="none" stroke="white" stroke-width="3"/>'),
]
def render(page, affiliate_note):
    def icon(shape):
        return '<svg viewBox="0 0 100 100" aria-hidden="true" focusable="false">'+shape+'</svg>'
    cards=''.join(f'<article class="hunt-card">{icon(shape)}<h3>{name}</h3><small>Unicorn treasure hunt · Leave this card here</small></article>' for name,shape in SYMBOLS)
    checks=''.join(f'<label class="hunt-match"><input type="checkbox">{icon(shape)}<span>{name}</span></label>' for name,shape in SYMBOLS)
    body='''<main id="main"><div class="page-intro"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / <a href="/tools/unicorn-party-games.html">Party games</a></div><span class="eyebrow">Free print-and-play activity</span><h1>Unicorn treasure hunt</h1><p>Help your unicorn find six magical symbols. Print the hiding cards and a matching sheet, then turn your party space into a treasure trail.</p><div class="hero-actions"><a class="button" href="#hunt-print">Get the free printables</a><a class="button button-light" href="#hunt-rules">How to play</a></div></div></div>
    <div class="article wrap hunt-page"><section id="hunt-rules"><h2>A party game you can set up in minutes</h2><p><strong>Suggested ages:</strong> 4–8 with an adult helper. <strong>Suggested play time:</strong> 10–15 minutes. Play together as one team or print a matching sheet for each child. The symbols work in black and white; children can match pictures without reading.</p><ol><li>Print one set of the six hiding cards. An adult cuts along the dotted borders.</li><li>Place the cards in six easy-to-reach spots within your agreed play area. Keep them visible enough to find without climbing or opening cupboards.</li><li>Give each child or team a matching sheet and a pencil. Leave the hiding cards in place so everyone can find them.</li><li>When a player spots a symbol, they tick the matching picture. Find all six to complete the quest.</li><li>Gather everyone to count the symbols and celebrate together. A prize is optional.</li></ol><p><strong>Make it easier:</strong> use one room and place cards in plain sight. <strong>Make it harder:</strong> spread the cards across a larger supervised area and give a warm-or-cold hint if someone gets stuck.</p></section>
    <section id="hunt-print"><h2>Print your treasure hunt</h2><p>The full set has two pages: six cut-out cards on the first and one player sheet on the second. Print extra copies of the player sheet for more children. Use A4 or Letter paper, portrait orientation, and turn off browser headers and footers for a cleaner result.</p><div class="hero-actions"><button class="button" type="button" data-hunt-print="all" hidden>Print full game</button><button class="button button-light" type="button" data-hunt-print="sheet" hidden>Print player sheet only</button></div><noscript><p>Use your browser’s Print menu to print the full two-page set.</p></noscript><p>You can also choose “Save as PDF” in your print menu. Free for personal party use. No sign-up required.</p></section>
    <section id="hunt-cards"><h2>Six magical hiding cards</h2><p class="print-caption">Adult: cut out and place these cards around your play area. Players leave them in place.</p><div class="hunt-card-grid">'''+cards+'''</div></section>
    <section id="hunt-sheet"><h2>My unicorn treasure hunt</h2><p>Name / team: __________________________________</p><p>Find each picture and tick its box. Leave the hiding cards where you found them!</p><div class="hunt-match-grid">'''+checks+'''</div><p class="hunt-finish">I found all six magical symbols!</p><small>Free printable from unicornsite.online</small></section>
    <section id="hunt-supplies"><h2>What you need — and optional party extras</h2><p>Paper, a printer and pencils are enough to play. Tape can help display the cards; check the surface first. You do not need a purchased game kit.</p>'''+affiliate_note()+'''<p>If you want a small shared celebration, compare <a href="https://www.amazon.com/s?k=unicorn+stickers+party+favors&amp;tag=unicornmagic2-20" target="_blank" rel="sponsored nofollow noopener noreferrer">unicorn sticker packs on Amazon</a> (paid link; search results). Check age guidance and how many separate sheets are included. Our <a href="/guides/unicorn-party-favor-ideas.html">party favor guide</a> has more ideas.</p><h2>Plan the rest of your unicorn party</h2><p><a href="/tools/unicorn-party-games.html#bingo">Make free bingo cards</a> for a quieter follow-up, use the <a href="/tools/unicorn-party-planner.html">party budget and supplies planner</a>, or plan dessert with the <a href="/tools/birthday-cake-servings-calculator.html">unicorn cake guide</a>.</p><h2>Can I play without a printer?</h2><p>Yes. Draw the six symbols on separate pieces of paper and copy them onto a matching sheet. You can also tick the sheet on this page for a shared team game; ticks clear when you reload.</p></section></div><script src="/assets/treasure-hunt.js" defer></script></main>'''
    return page('Free Printable Unicorn Treasure Hunt | Unicorn Finds','Print a free unicorn treasure hunt with six picture cards, a matching player sheet and easy party-game instructions. No sign-up needed.','/tools/unicorn-treasure-hunt.html',body).replace('</head>','<link rel="stylesheet" href="/assets/treasure-hunt.css"></head>')
